# .github/workflows/my-build.yml
name: Test Build for Windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8"]
    steps:
     - uses: actions/checkout@v1
     - uses: conda-incubator/setup-miniconda@v2
       with:
         miniconda-version: "latest"
         auto-update-conda: true
         add-pip-as-python-dependency: true
         python-version: ${{ matrix.python-version }}
     - name: Installing required conda packages
       run: |
         conda install -c default -c anaconda -c msys2 numpy libpython m2w64-toolchain
     - name: Test with pytest
       run: |
         pip install -e .
         python docs/tutorial/example.py

  build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04, macOS-10.15]

      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          name: Install Python

        - name: Install cibuildwheel
          run: python -m pip install numpy cibuildwheel==1.7.4

        - name: Build wheels
          run: python -m cibuildwheel --output-dir wheelhouse
          env:
            CIBW_SKIP: "cp27-* pp27-*"  # skip Python 2.7 wheels
        
        - uses: actions/upload-artifact@v2
          with:
            path: ./wheelhouse/*.whl
        - name: Test with pytest
          run: |
            ls -l ./wheelhouse
