# .github/workflows/my-build.yml
name: Test Build for Windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8"]
    steps:
     - uses: actions/checkout@v1
     - uses: conda-incubator/setup-miniconda@v2
       with:
         miniconda-version: "latest"
         auto-update-conda: true
         add-pip-as-python-dependency: true
         python-version: ${{ matrix.python-version }}
     - name: Installing required conda packages
       run: |
         conda install -c default -c anaconda -c msys2 numpy libpython m2w64-toolchain
     - name: Test with pytest
       run: |
         pip install -e .
         python docs/tutorial/example.py